apiVersion: v1
kind: Pod
metadata:
  name: symlink-test
spec:
  containers:
    - name: alma
      image: almalinux:9.2
      command: [sleep "infinity"]
      imagePullPolicy: IfNotPresent
    - name: ubuntu
      image: ubuntu:latest
      command: [sleep "infinity"]
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
