kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.100.1.0/24
  kubeProxyMode: none
nodes:
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress=true"
  extraPortMappings:
    - containerPort: 30000
      hostPort: 80
      listenAddress: 127.0.0.1
      protocol: TCP
- role: worker
- role: worker
