kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.100.1.0/24
  kubeProxyMode: none
nodes:
- role: control-plane
- role: worker
  labels:
    ingress: "true"
    topology.ytsaurus.tech/rack: "first"
    topology.ytsaurus.tech/dc: "alpha"
  extraPortMappings:
    - containerPort: 30000
      hostPort: 80
      listenAddress: 127.0.0.1
      protocol: TCP
- role: worker
  labels:
    topology.ytsaurus.tech/rack: "second"
    topology.ytsaurus.tech/dc: "alpha"
- role: worker
  labels:
    topology.ytsaurus.tech/rack: "first"
    topology.ytsaurus.tech/dc: "beta"
